INSERT INTO documents (
    id, title, document_type, source, summary, content,
    department, version, status, effective_date
) VALUES
(
    'sop-001',
    'Prior Authorization Submission Procedure',
    'SOP',
    'UM-SOP-PA-Submit-2026.pdf',
    'Steps to submit a complete prior authorization request to a commercial payer.',
    'Submit prior authorization requests only after eligibility is confirmed. Include the member ID, ordering provider NPI, requested CPT/HCPCS codes, diagnosis codes, and supporting clinical notes. If the payer portal is unavailable, fax the packet and log the confirmation number in the UM tracker.',
    'Utilization Management',
    '1.2',
    'ACTIVE',
    '2026-01-15'
),
(
    'sop-002',
    'Eligibility Verification Procedure',
    'SOP',
    'Access-SOP-Eligibility-2026.pdf',
    'Standard steps to verify coverage before scheduling or authorizing services.',
    'Verify eligibility on the date of service using the payer portal or EDI 270/271. Confirm plan name, effective dates, in-network status, and copay or deductible. If coverage is inactive, stop the authorization and notify the scheduling team.',
    'Patient Access',
    '1.1',
    'ACTIVE',
    '2026-01-08'
),
(
    'sop-003',
    'Claim Denial Handling Procedure',
    'SOP',
    'Claims-SOP-Denial-2026.pdf',
    'How to review, document, and route a denied claim for correction or appeal.',
    'When a claim is denied, identify the CARC/RARC codes, confirm whether the denial is medical or administrative, and notify the submitter within two business days. Do not close the case until missing documentation is received or the appeal window expires.',
    'Claims',
    '2.0',
    'ACTIVE',
    '2026-02-01'
),
(
    'sop-004',
    'Appeal Process Procedure',
    'SOP',
    'Appeals-SOP-Process-2026.pdf',
    'How to prepare, submit, and track a first-level appeal for a denied authorization or claim.',
    'Confirm the payer appeal window before writing the letter. Attach the denial notice, relevant clinical notes, and a point-by-point medical necessity rationale. Log the appeal ID in the tracker and set a follow-up date before the payer due date.',
    'Appeals',
    '1.3',
    'ACTIVE',
    '2026-01-20'
),
(
    'sop-005',
    'Referral Requirements Procedure',
    'SOP',
    'Access-SOP-Referral-2026.pdf',
    'When a primary care referral is required before specialty evaluation.',
    'For HMO plans, obtain a PCP referral before specialty evaluation in orthopedics, cardiology, and neurology. Confirm the referral number is valid and unexpired. Claims without a matching referral are denied as not authorized.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-03-01'
),
(
    'payer-001',
    'MRI Prior Authorization Requirements',
    'PAYER_RULE',
    'Payer-Northstar-MRI-Rules.pdf',
    'Northstar Health requires prior authorization for outpatient MRI except in listed emergencies.',
    'Northstar Health requires prior authorization for outpatient MRI of the brain, spine, and joints. Include conservative therapy notes for at least four weeks when requesting lumbar MRI. Emergency department MRI performed during an acute visit does not require prior authorization.',
    'Payer Operations',
    '2026.1',
    'ACTIVE',
    '2026-01-01'
),
(
    'payer-002',
    'CT Scan Authorization Requirements',
    'PAYER_RULE',
    'Payer-Summit-CT-Rules.pdf',
    'Summit Care requires authorization for non-emergent CT except when cancer staging criteria are met.',
    'Summit Care requires prior authorization for non-emergent outpatient CT. Cancer staging CT is exempt when an oncology diagnosis and staging intent are documented. Contrast versus non-contrast must be specified on the authorization request.',
    'Payer Operations',
    '2026.2',
    'ACTIVE',
    '2026-02-15'
),
(
    'payer-003',
    'Medical Necessity Documentation Requirements',
    'PAYER_RULE',
    'Payer-MedNec-Docs-Rules.pdf',
    'Clinical elements payers expect when reviewing medical necessity.',
    'Medical necessity packets must include relevant history, physical findings, prior treatments, and the clinical rationale for the requested service. Imaging requests also need the suspected diagnosis and why a lower-intensity alternative is not appropriate.',
    'Clinical Review',
    '1.0',
    'ACTIVE',
    '2026-03-01'
),
(
    'payer-004',
    'Authorization Expiration Rules',
    'PAYER_RULE',
    'Payer-Auth-Expiry-Rules.pdf',
    'How long approved authorizations remain valid and when to request an extension.',
    'Most commercial authorizations are valid for 30 to 90 days. Review authorizations that expire within 14 days. If the service is still planned, request an extension with updated clinicals. Expired unused authorizations should be marked unused, not denied.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-04-01'
),
(
    'payer-005',
    'Clinical Documentation Requirements',
    'PAYER_RULE',
    'Payer-Common-CO16-Rules.pdf',
    'How payers apply documentation denials and what to attach on resubmission.',
    'Payers often deny for missing clinical documentation when the progress note, imaging report, or order is absent. Resubmit with the complete note, the signed order, and the original claim number. Do not open a new claim if the payer accepts a corrected claim.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-03-10'
),
(
    'case-001',
    'Sample Case: Approved MRI Prior Authorization',
    'PAST_CASE',
    'Case-UM-8801-Approved.docx',
    'Fictional case where lumbar MRI was approved after conservative therapy notes were attached.',
    'Case UM-8801 (fictional) requested lumbar MRI for persistent radiculopathy. The first submission lacked physical therapy notes. After the clinic attached four weeks of conservative therapy, Northstar Health approved the MRI for 45 days.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-05-02'
),
(
    'case-002',
    'Sample Case: Denied Authorization for Missing Clinicals',
    'PAST_CASE',
    'Case-UM-8807-Denied.docx',
    'Fictional denial issued because the request included an order but no progress note.',
    'Case UM-8807 (fictional) requested CT abdomen. The packet included an order only. Summit Care denied for missing clinical documentation. The team obtained the clinic progress note and resubmitted as a reconsideration rather than a new request.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-05-18'
),
(
    'case-003',
    'Sample Case: Missing Documentation on a Claim',
    'PAST_CASE',
    'Case-Claims-4412.docx',
    'Fictional claim denied because required clinical attachments were not submitted.',
    'Case 4412 (fictional) was denied for missing documentation. The team attached the operative note and resubmitted with the original claim number. Future claims for that CPT now use a documentation checklist before billing.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-06-01'
),
(
    'case-004',
    'Sample Case: Appeal Approved After Medical Necessity Denial',
    'PAST_CASE',
    'Case-Appeals-5520.docx',
    'Fictional appeal that overturned a medical necessity denial for physical therapy visits.',
    'Case AP-5520 (fictional) was denied as not medically necessary after eight PT visits. The appeal included updated functional scores and a plan for four additional visits. The payer overturned the denial and authorized the remaining visits.',
    'Appeals',
    '1.0',
    'ACTIVE',
    '2026-06-12'
),
(
    'case-005',
    'Sample Case: Eligibility Issue Before Authorization',
    'PAST_CASE',
    'Case-Access-6604.docx',
    'Fictional case closed after eligibility showed the plan was termed before the date of service.',
    'Case EL-6604 (fictional) started an MRI authorization, then eligibility returned as termed effective two days earlier. Authorization was stopped, scheduling was notified, and the member was asked to provide updated insurance before any new request.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-06-20'
),
(
    'sop-006',
    'Prior Authorization Intake SOP',
    'SOP',
    'Synthetic-PA-Intake-SOP-2026.pdf',
    'Workflow for receiving, validating, submitting, and tracking prior authorization requests.',
    'Receive each prior authorization request, also called a PA request or authorization request, through the intake queue. Verify member and service details, then confirm the procedure or service code against the order. Check payer requirements for prior auth, collect supporting clinical documentation, and submit the request through the payer portal or fax. Capture the authorization or reference number, track status until approval or denial, and document the outcome in the UM tracker. Do not start the service until status is confirmed unless a documented urgent exception applies.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-01-01'
),
(
    'sop-007',
    'Eligibility Verification SOP',
    'SOP',
    'Synthetic-Eligibility-SOP-2026.pdf',
    'How to complete insurance eligibility, coverage verification, and benefits verification before service.',
    'Complete eligibility and insurance eligibility checks on or before the date of service. Confirm active coverage, effective date, and termination date. Record plan type, member ID, deductible, copay, coinsurance, and benefit limitations. Note whether an authorization requirement applies. Document the verification result, including the portal or EDI 270/271 confirmation. If coverage is inactive, stop scheduling and notify the requester. Benefits verification is not a guarantee of payment.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-01-05'
),
(
    'sop-008',
    'Claim Denial Handling SOP',
    'SOP',
    'Synthetic-Claim-Denial-SOP-2026.pdf',
    'Steps to review a denied claim or claim rejected notice and choose correction or appeal.',
    'When a claim denial or denied claim arrives, identify the denial reason from the remittance advice. Validate coding, authorization, eligibility, and timely filing. Check for missing documentation. For administrative errors, correct and resubmit. For medical necessity or authorization denials, route to appeal. Document the action taken, the CARC/RARC codes, and the follow-up date. Denial handling is complete only after correction, appeal, or a written write-off decision.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-01-12'
),
(
    'sop-009',
    'Prior Authorization Status Follow-Up SOP',
    'SOP',
    'Synthetic-PA-Status-Followup-SOP-2026.pdf',
    'How to follow up on pending authorization and record prior auth status from the payer.',
    'Open the UM tracker daily for pending authorization and follow up authorization worklists. Look up authorization status in the payer portal using the reference number. If the portal is unavailable, complete phone follow-up and log the call. Record pending status, a request for additional information, approval, denial, and the expiration date. If additional information is required, notify the ordering department the same day. Do not close a prior auth status item until a final determination or expiration is documented.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-01-18'
),
(
    'sop-010',
    'Medical Necessity Documentation SOP',
    'SOP',
    'Synthetic-MedNec-Docs-SOP-2026.pdf',
    'How to assemble clinical documentation and supporting documentation for medical necessity review.',
    'Medical necessity packets must include diagnosis, symptoms, previous treatment, imaging results, and physician notes. Document conservative treatment already tried and the clinical indication for the requested service. Supporting documentation should match the ordered procedure and date of service. Incomplete clinical documentation is a common reason for denial. This SOP describes operational packet assembly only and does not make clinical treatment decisions.',
    'Clinical Review',
    '1.0',
    'ACTIVE',
    '2026-01-22'
),
(
    'sop-011',
    'Appeal Submission SOP',
    'SOP',
    'Synthetic-Appeal-Submission-SOP-2026.pdf',
    'How to prepare and submit a claim appeal, authorization appeal, or denial appeal.',
    'Review the denial letter and identify the appeal deadline before drafting. Gather supporting documentation, including the original denial, clinical notes, and medical necessity rationale. Prepare the appeal packet, submit the appeal through the payer channel required for that product, and obtain confirmation. Follow status until overturn, uphold, or withdrawal. Log the claim appeal or authorization appeal identifier in the tracker. Missed deadlines are documented as untimely and are not submitted without supervisor review.',
    'Appeals',
    '1.0',
    'ACTIVE',
    '2026-01-25'
),
(
    'sop-012',
    'Referral Verification SOP',
    'SOP',
    'Synthetic-Referral-Verification-SOP-2026.pdf',
    'How to confirm specialist referral and referral requirement before the visit.',
    'Determine whether a referral is required for the plan and specialty. Confirm the referring provider, specialist, referral number, effective dates, and number of visits. Check the authorization relationship when the referral is tied to a prior authorization. A specialist referral that is missing, expired, or for the wrong provider is not valid. Document the verification result before scheduling. Claims without a required referral are at high risk of denial.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-02-02'
),
(
    'sop-013',
    'Authorization Expiration SOP',
    'SOP',
    'Synthetic-Auth-Expiration-SOP-2026.pdf',
    'How to handle an authorization expired or expired prior auth before the service date.',
    'Check authorization effective dates against the planned service date. Identify remaining visits and whether the authorization expiration has already passed. If the service is still needed, request an extension or a new authorization and document the updated authorization number. An expired prior auth must not be used for billing. Notify scheduling when remaining visits are zero or the authorization expired before the appointment.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-02-08'
),
(
    'sop-014',
    'Missing Clinical Documentation SOP',
    'SOP',
    'Synthetic-Missing-Clinicals-SOP-2026.pdf',
    'How to request missing documentation, missing clinicals, and additional documentation from the source department.',
    'Identify missing documents from the payer request or denial. Request records from the provider or department, including clinical records needed for medical necessity. Validate receipt, resubmit to the payer, and track completion until the item is closed. Missing clinicals should be requested the same day they are identified. Do not resubmit a packet that still lacks the listed additional documentation.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-02-14'
),
(
    'sop-015',
    'Urgent Prior Authorization SOP',
    'SOP',
    'Synthetic-Urgent-PA-SOP-2026.pdf',
    'Operational workflow for urgent authorization, expedited authorization, and urgent prior auth requests.',
    'Determine urgency using the payer expedited criteria and the documented clinical situation. Mark the request as urgent prior auth or expedited authorization in the tracker. Collect the required clinical information, complete expedited submission, and follow up within the payer time frame. Urgent authorization is an operational pathway only. This SOP does not make clinical treatment decisions and does not substitute for emergency department care.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-02-20'
),
(
    'sop-016',
    'Authorization Not Required Verification SOP',
    'SOP',
    'Synthetic-Auth-Not-Required-SOP-2026.pdf',
    'How to confirm no authorization required, auth not required, or NPR status before service.',
    'Verify payer policy for the service and procedure code, including network status and service location. If the result is authorization not required, also called auth not required or NPR, record the payer confirmation and reference information. Authorization verification must be dated and stored in the encounter record. Do not assume NPR from a prior visit. If policy is unclear, obtain written payer confirmation before scheduling.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-02-26'
),
(
    'sop-017',
    'Insurance Information Update SOP',
    'SOP',
    'Synthetic-Insurance-Update-SOP-2026.pdf',
    'How to complete an insurance update when a member reports new insurance.',
    'When staff receive an insurance update or a request to update insurance, collect payer name, member ID, group number, and effective date. Verify coverage before replacing the previous plan on the account. New insurance should be stored only as operational registration data. Do not enter extra personal identifiers beyond what is required to bill. After coverage is verified, update the record and notify scheduling and UM if an open authorization used the prior payer.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-03-04'
),
(
    'sop-018',
    'Duplicate Claim Review SOP',
    'SOP',
    'Synthetic-Duplicate-Claim-SOP-2026.pdf',
    'How to review a duplicate claim, duplicate denial, or duplicate billing notice.',
    'Compare claim number, service date, and procedure against the prior submission. Review the payer response to decide whether the item is a true duplicate denial or a duplicate billing error. If the first claim is still open, do not submit another original. Determine whether a corrected claim or an appeal is required. Document the comparison and the action taken. Duplicate claim work is complete when the payer accepts one claim and extras are voided or appealed.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-03-10'
),
(
    'sop-019',
    'Timely Filing Review SOP',
    'SOP',
    'Synthetic-Timely-Filing-SOP-2026.pdf',
    'How to evaluate timely filing, filing limit, and claim submission deadline disputes.',
    'Confirm the payer filing period and the original submission date. Collect proof of timely filing when the claim submission deadline is disputed. If the original claim was late, document the finding and do not invent a new original date. Use a corrected claim only when the original was timely and the content must change. Appeal documentation should include the filing limit policy, submission proof, and the denial notice.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-03-16'
),
(
    'sop-020',
    'Coordination of Benefits SOP',
    'SOP',
    'Synthetic-COB-SOP-2026.pdf',
    'How to identify primary insurance and secondary insurance and complete coordination of benefits.',
    'Identify the primary payer and secondary payer using coordination of benefits, also called COB, rules. Verify coverage on both plans. Collect the primary EOB or remittance information before billing the secondary insurance. Submit the secondary claim with the primary payment details attached. Do not bill both plans as primary. Document the COB determination, effective dates, and any payer remarks about other coverage.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-03-22'
),
(
    'sop-021',
    'Provider Network Verification SOP',
    'SOP',
    'Synthetic-Network-Verification-SOP-2026.pdf',
    'How to complete network verification for in network or out of network status.',
    'Verify the payer, plan, provider, facility, and service location against the provider network directory. Record whether the result is in network or out of network and the effective date. Network verification must be done for the rendering provider and the place of service. Document the verification result, including directory source and date checked. Out of network findings should be communicated before the service when time allows.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-03-28'
),
(
    'sop-022',
    'Pre-Service Financial Clearance SOP',
    'SOP',
    'Synthetic-Financial-Clearance-SOP-2026.pdf',
    'Operational steps for financial clearance and pre service verification of estimated patient responsibility.',
    'Complete financial clearance before the service by confirming eligibility, authorization, referral, and benefit information. Estimate deductible, copay, coinsurance, and remaining patient responsibility. Pre service verification is informational only and is not a promise of final charges. Document the estimate, the source of benefits, and any missing clearance items. Do not provide clinical advice as part of financial clearance.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-04-03'
),
(
    'sop-023',
    'Claim Correction SOP',
    'SOP',
    'Synthetic-Claim-Correction-SOP-2026.pdf',
    'How to identify a claim error and submit a corrected claim or resubmit claim packet.',
    'Identify the claim error from the remittance or internal audit. Correct demographic, coding, or authorization information as appropriate. Use the corrected claim indicator and include the original claim reference. Submit the corrected claim through the payer channel that accepts replacements, then track the response. Do not resubmit claim as a new original if a replacement is required. Claim correction is complete when the payer acknowledges the replacement or issues a new remittance.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-04-09'
)
ON CONFLICT (id) DO NOTHING;
