INSERT INTO documents (
    id, title, document_type, source, summary, content,
    department, version, status, effective_date
) VALUES
(
    'sop-001',
    'Prior Authorization Submission Procedure',
    'SOP',
    'UM-SOP-PA-Submit-2026.pdf',
    'Steps to submit a complete prior authorization request to a commercial payer.',
    'Submit prior authorization requests only after eligibility is confirmed. Include the member ID, ordering provider NPI, requested CPT/HCPCS codes, diagnosis codes, and supporting clinical notes. If the payer portal is unavailable, fax the packet and log the confirmation number in the UM tracker.',
    'Utilization Management',
    '1.2',
    'ACTIVE',
    '2026-01-15'
),
(
    'sop-002',
    'Eligibility Verification Procedure',
    'SOP',
    'Access-SOP-Eligibility-2026.pdf',
    'Standard steps to verify coverage before scheduling or authorizing services.',
    'Verify eligibility on the date of service using the payer portal or EDI 270/271. Confirm plan name, effective dates, in-network status, and copay or deductible. If coverage is inactive, stop the authorization and notify the scheduling team.',
    'Patient Access',
    '1.1',
    'ACTIVE',
    '2026-01-08'
),
(
    'sop-003',
    'Claim Denial Handling Procedure',
    'SOP',
    'Claims-SOP-Denial-2026.pdf',
    'How to review, document, and route a denied claim for correction or appeal.',
    'When a claim is denied, identify the CARC/RARC codes, confirm whether the denial is medical or administrative, and notify the submitter within two business days. Do not close the case until missing documentation is received or the appeal window expires.',
    'Claims',
    '2.0',
    'ACTIVE',
    '2026-02-01'
),
(
    'sop-004',
    'Appeal Process Procedure',
    'SOP',
    'Appeals-SOP-Process-2026.pdf',
    'How to prepare, submit, and track a first-level appeal for a denied authorization or claim.',
    'Confirm the payer appeal window before writing the letter. Attach the denial notice, relevant clinical notes, and a point-by-point medical necessity rationale. Log the appeal ID in the tracker and set a follow-up date before the payer due date.',
    'Appeals',
    '1.3',
    'ACTIVE',
    '2026-01-20'
),
(
    'sop-005',
    'Referral Requirements Procedure',
    'SOP',
    'Access-SOP-Referral-2026.pdf',
    'When a primary care referral is required before specialty evaluation.',
    'For HMO plans, obtain a PCP referral before specialty evaluation in orthopedics, cardiology, and neurology. Confirm the referral number is valid and unexpired. Claims without a matching referral are denied as not authorized.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-03-01'
),
(
    'payer-001',
    'MRI Prior Authorization Requirements',
    'PAYER_RULE',
    'Payer-Northstar-MRI-Rules.pdf',
    'Northstar Health requires prior authorization for outpatient MRI except in listed emergencies.',
    'Northstar Health requires prior authorization for outpatient MRI of the brain, spine, and joints. Include conservative therapy notes for at least four weeks when requesting lumbar MRI. Emergency department MRI performed during an acute visit does not require prior authorization.',
    'Payer Operations',
    '2026.1',
    'ACTIVE',
    '2026-01-01'
),
(
    'payer-002',
    'CT Scan Authorization Requirements',
    'PAYER_RULE',
    'Payer-Summit-CT-Rules.pdf',
    'Summit Care requires authorization for non-emergent CT except when cancer staging criteria are met.',
    'Summit Care requires prior authorization for non-emergent outpatient CT. Cancer staging CT is exempt when an oncology diagnosis and staging intent are documented. Contrast versus non-contrast must be specified on the authorization request.',
    'Payer Operations',
    '2026.2',
    'ACTIVE',
    '2026-02-15'
),
(
    'payer-003',
    'Medical Necessity Documentation Requirements',
    'PAYER_RULE',
    'Payer-MedNec-Docs-Rules.pdf',
    'Clinical elements payers expect when reviewing medical necessity.',
    'Medical necessity packets must include relevant history, physical findings, prior treatments, and the clinical rationale for the requested service. Imaging requests also need the suspected diagnosis and why a lower-intensity alternative is not appropriate.',
    'Clinical Review',
    '1.0',
    'ACTIVE',
    '2026-03-01'
),
(
    'payer-004',
    'Authorization Expiration Rules',
    'PAYER_RULE',
    'Payer-Auth-Expiry-Rules.pdf',
    'How long approved authorizations remain valid and when to request an extension.',
    'Most commercial authorizations are valid for 30 to 90 days. Review authorizations that expire within 14 days. If the service is still planned, request an extension with updated clinicals. Expired unused authorizations should be marked unused, not denied.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-04-01'
),
(
    'payer-005',
    'Clinical Documentation Requirements',
    'PAYER_RULE',
    'Payer-Common-CO16-Rules.pdf',
    'How payers apply documentation denials and what to attach on resubmission.',
    'Payers often deny for missing clinical documentation when the progress note, imaging report, or order is absent. Resubmit with the complete note, the signed order, and the original claim number. Do not open a new claim if the payer accepts a corrected claim.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-03-10'
),
(
    'case-001',
    'Sample Case: Approved MRI Prior Authorization',
    'PAST_CASE',
    'Case-UM-8801-Approved.docx',
    'Fictional case where lumbar MRI was approved after conservative therapy notes were attached.',
    'Case UM-8801 (fictional) requested lumbar MRI for persistent radiculopathy. The first submission lacked physical therapy notes. After the clinic attached four weeks of conservative therapy, Northstar Health approved the MRI for 45 days.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-05-02'
),
(
    'case-002',
    'Sample Case: Denied Authorization for Missing Clinicals',
    'PAST_CASE',
    'Case-UM-8807-Denied.docx',
    'Fictional denial issued because the request included an order but no progress note.',
    'Case UM-8807 (fictional) requested CT abdomen. The packet included an order only. Summit Care denied for missing clinical documentation. The team obtained the clinic progress note and resubmitted as a reconsideration rather than a new request.',
    'Utilization Management',
    '1.0',
    'ACTIVE',
    '2026-05-18'
),
(
    'case-003',
    'Sample Case: Missing Documentation on a Claim',
    'PAST_CASE',
    'Case-Claims-4412.docx',
    'Fictional claim denied because required clinical attachments were not submitted.',
    'Case 4412 (fictional) was denied for missing documentation. The team attached the operative note and resubmitted with the original claim number. Future claims for that CPT now use a documentation checklist before billing.',
    'Claims',
    '1.0',
    'ACTIVE',
    '2026-06-01'
),
(
    'case-004',
    'Sample Case: Appeal Approved After Medical Necessity Denial',
    'PAST_CASE',
    'Case-Appeals-5520.docx',
    'Fictional appeal that overturned a medical necessity denial for physical therapy visits.',
    'Case AP-5520 (fictional) was denied as not medically necessary after eight PT visits. The appeal included updated functional scores and a plan for four additional visits. The payer overturned the denial and authorized the remaining visits.',
    'Appeals',
    '1.0',
    'ACTIVE',
    '2026-06-12'
),
(
    'case-005',
    'Sample Case: Eligibility Issue Before Authorization',
    'PAST_CASE',
    'Case-Access-6604.docx',
    'Fictional case closed after eligibility showed the plan was termed before the date of service.',
    'Case EL-6604 (fictional) started an MRI authorization, then eligibility returned as termed effective two days earlier. Authorization was stopped, scheduling was notified, and the member was asked to provide updated insurance before any new request.',
    'Patient Access',
    '1.0',
    'ACTIVE',
    '2026-06-20'
)
ON CONFLICT (id) DO NOTHING;
